---
title: "Simulate SHM Data"
output:
  html_document:
    df_print: paged
  html_notebook: default
  word_document: default
  pdf_document: default
---

```{r, echo=FALSE, warning=FALSE}
library(ggplot2) # gorgeous plots
library(gridExtra) # useful for plotting in grids
library(MASS) #contains boxcox and much more
library(olsrr) #makes some nice plots to check assumptions
library(stats)
library(nlme) # contains gls = generalized least squares
library(pracma) #practical math...contains some functions from matlab
library(ggResidpanel)
library(car) # Need this for durbinWatsonTest
library(tibble)
library(survival)
library(corrplot)
library(SuppDists)

```


```{r}
set.seed(1)
# Setup the parameters for the simulation_______________________________________
numSpecimens=60
numObservations = 100
start=1

time = seq(start,numObservations+start,length.out=numObservations)

lambda_sim=0.3

# Simulate a Pearson Correlation distribution
rho=abs(rPearson(n=60,N=100,rho=0.94)) # Value from auto-correlation test of all the data

 for(index in 1:numSpecimens){
   if(rho[index]>1){rho[index]=1}
   if(rho[index]<0){rho[index]=0}
   index = index + 1
 }

## Use burn-in to simulate a crack that is not detectable yet.
burn_in_time = rnorm(numSpecimens,mean=(numObservations/2),sd=3)

y_vect=0
y_prev=0

# Relationship between x and time
b0xt = rnorm(n=numSpecimens, mean=0, sd=0.15)
b1xt = rnorm(n=numSpecimens, mean=0.015, sd=0.002)
# Relationship between x and y
b0xy = rnorm(n=numSpecimens, mean=7.0, sd=2.1)
b1xy = rnorm(n=numSpecimens, mean=31.0, sd=5.3)
# Relationship between time and y
b0ty = rnorm(n=numSpecimens, mean=-0.31, sd=4.7)
b1ty = rnorm(n=numSpecimens, mean=0.50, sd=0.09)

data.ts = data.frame(specimen =0, time = 0, x=0, y=0, y.orig=0, y.trans=0,rho=0)

# A gamma distribution represents the distribution of stdev.
stdev = c(rgamma(n=numObservations/4,shape=7.8, rate=4.4),
          rgamma(n=numObservations/4,shape=2.5, rate=3.3),
          rgamma(n=numObservations/4,shape=3.7, rate=10.1),
          rgamma(n=numObservations/4,shape=6.1, rate=20.2))

# Create the AR1 Data____________________________________________________________________
for(specimen in 1:numSpecimens){
  y_vect=0
  y_prev=0
  rho_curr = rho[specimen]
  for(index in time[1]:time[numObservations]){
       burn_in=1
        x_curr=b0xt[specimen]+b1xt[specimen]*index 
        x_prev=b0xt[specimen]+b1xt[specimen]*(index-1)
        if(x_curr<=0.3){burn_in=0.2+2*(rnorm(1,x_curr,0.05))}
        y_curr=b0xy[specimen]+b1xy[specimen]*x_curr
        y_prev=b0xy[specimen]+b1xy[specimen]*x_prev
        y_new =burn_in*((1-rho_curr)*y_curr+rho_curr*y_prev) + rnorm(n=1,mean=0,sd=stdev[index])
      y_vect = c(y_vect,y_new)
      time = c(time,index)
      y_prev=y_new
      index = index+1
  }
  data.ts.new = 
    data.frame(specimen = specimen, 
               time = time[1:numObservations], 
               x=b0xt[specimen]+b1xt[specimen]*time[1:numObservations], 
               y=y_vect[1:numObservations], 
               y.orig=(y_vect[1:numObservations]*lambda_sim+1)^(1/lambda_sim), 
               y.trans=y_vect[1:numObservations], 
               rho=rep(rho_curr,numObservations))
  data.ts=rbind(data.ts, data.ts.new)
}

data.ts = subset(data.ts,specimen>0)
data.ts.pos = subset(data.ts,x>0)

# Apply the Box Cox__________________________________________
bc<-boxcox(y.orig ~ x, data=subset(data.ts,y.orig>0), na.action=na.omit, lambda = seq(-2,2,by=0.01),
                    plotit = FALSE, eps = .Machine$double.eps/2, 
                    xlab = expression(lambda), ylab = "LL")
lambda_new <- bc$x[which.max(bc$y)]
print(paste("Box Cox Lambda is ",lambda_new))
data.ts$y.trans=(data.ts$y.orig^lambda_new-1)/lambda_new


```

```{r}

#Plot the data_______________________________________________
ggplot(data.ts,(aes(x=x,y=time,colour=as.factor(specimen))))+geom_line()+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))
ggplot(data.ts,(aes(x=x,colour=as.factor(specimen))))+geom_density()+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))

ggplot(data.ts, aes(x=x, y=y, colour=as.factor(specimen)))+geom_point()+#geom_line()+
  ylab("Simulated Box Cox Response")+xlab("Defect Size (a)")+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))#+ylim(0,10)+xlim(0,0.32)

ggplot(data.ts, aes(x=x, y=y.orig, colour=as.factor(specimen)))+geom_point()+#geom_line()+
  ylab("Response")+xlab("Defect Size (a)")+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))#+ylim(0,10)+xlim(0,0.32)

ggplot(data.ts, aes(x=time, y=y, colour=as.factor(specimen)))+geom_point()+#geom_line()+
  ylab("Simulated Box Cox Response")+xlab("Time")+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))#+ylim(0,10)+xlim(0,0.32)

ggplot(data.ts, aes(x=time, y=y.orig, colour=as.factor(specimen)))+geom_point()+#geom_line()+
  ylab("Response")+xlab("Time")+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))#+ylim(0,10)+xlim(0,0.32)

ggplot(data.ts, aes(x=x, y=y.trans, colour=as.factor(specimen)))+geom_point()+#geom_line()+
  ylab("Box Cox Response")+xlab("Defect Size (a)")+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))#+ylim(0,10)+xlim(0,0.32)

ggplot(data.ts, aes(x=time, y=y.trans, colour=as.factor(specimen)))+geom_point()+#geom_line()+
  ylab("Box Cox Response")+xlab("Time")+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))#+ylim(0,10)+xlim(0,0.32)


ggplot(data.ts, aes(x=x, y=y.orig, colour=as.factor(specimen)))+geom_point()+#geom_line()+
  ylab("Response")+xlab("Defect Size (a)")+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))+ylim(0,500)+xlim(-0.2,0.75)
```



When does each specimen go positive and when does it reach y_dec in response?
```{r}
y_dec=150
data=subset(data.ts,specimen==1)
data <- data[order(data$x,data$y.orig),] 
first.df = data.frame(
  specimen         = 1,
  x_1st_positive = subset(data,x>0)[1,]$x,
  obs_1st_positive = subset(data,x>0)[1,]$time,
  response_1st_positive=subset(data,x>0)[1,]$y.orig,
  x_1st_y_dec =  subset(data,y.orig>=y_dec)[1,]$x,
  obs_1st_y_dec = subset(data,y.orig>=y_dec)[1,]$time,
  response_1st_y_dec=subset(data,y.orig>=y_dec)[1,]$y.orig
)

for(specimen in 2:60){
  data=subset(data.ts,specimen==specimen)
  data <- data[order(data$x,data$y.orig),] 
  first.df.new = data.frame(
  specimen         = specimen,
  x_1st_positive = subset(data,x>0)[1,]$x,
  obs_1st_positive = subset(data,x>0)[1,]$time,
  response_1st_positive=subset(data,x>0)[1,]$y.orig,
  x_1st_y_dec =  subset(data,y.orig>=y_dec)[1,]$x,
  obs_1st_y_dec = subset(data,y.orig>=y_dec)[1,]$time,
  response_1st_y_dec=subset(data,y.orig>=y_dec)[1,]$y.orig
)
  first.df = rbind(first.df,first.df.new)
}

summary(first.df)
ggplot(first.df)+geom_density(aes(obs_1st_positive),colour="red")+theme_bw()+xlab("Observation")+ggtitle("Observation at x>0")
ggplot(first.df)+geom_density(aes(obs_1st_y_dec),colour="blue")+theme_bw()+xlab("Observation")+ggtitle("Observation at Response=y_dec")
ggplot(first.df)+geom_density(aes(obs_1st_positive),colour="red")+geom_density(aes(obs_1st_y_dec),colour="blue")+theme_bw()+xlab("Observation")+ggtitle("Observation at x>0 and Response=y_dec")
```


Models for data.ts between x and response
```{r}
data=subset(data.ts,specimen==1)
model=lm(y.trans~x,data=data) 
DW=durbinWatsonTest(model)
data=subset(data,y.orig>0)
bc<-boxcox(y.orig~x, data=data, na.action=na.omit, lambda = seq(-2,2,by=0.01),
                    plotit = FALSE, eps = .Machine$double.eps/2, 
                    xlab = expression(lambda), ylab = "LL")
lambda <- bc$x[which.max(bc$y)]

model.df = data.frame(
  specimen     = 1,
  intercept    = model$coefficients[[1]],
  slope        = model$coefficients[[2]],
  intercept.se = summary(model)[4]$coefficients[3],
  slope.se     = summary(model)[4]$coefficients[4],
  sigma        = summary(model)$sigma,
  variance     = (summary(model)$sigma)^2,
  r.squared    = summary(model)$r.squared,
  var.intercept= summary(model)$cov[1],
  covariance   = summary(model)$cov[2],
  var.slope    = summary(model)$cov[4],
  aic          = AIC(model),
  bic          = BIC(model),
  autocorr     = DW[[1]],
  dw_stat      = DW[[2]],
  dw_pval      = DW[[3]],
  lambda       = lambda
)

for(specimen in 2:60){
  data=subset(data.ts,specimen==specimen)
  model=lm(y.trans~x,data=data) 
  DW=durbinWatsonTest(model)
  data=subset(data,y.orig>0)
  bc<-boxcox(y.orig~x, data=data, na.action=na.omit, lambda = seq(-2,2,by=0.01),
                    plotit = FALSE, eps = .Machine$double.eps/2, 
                    xlab = expression(lambda), ylab = "LL")
  lambda <- bc$x[which.max(bc$y)]
  model.df.new = data.frame(
    specimen     = specimen,
    intercept    = model$coefficients[[1]],
    slope        = model$coefficients[[2]],
    intercept.se = summary(model)[4]$coefficients[3],
    slope.se     = summary(model)[4]$coefficients[4],
    sigma        = summary(model)$sigma,
    variance     = (summary(model)$sigma)^2,
    r.squared    = summary(model)$r.squared,
    var.intercept= summary(model)$cov[1],
    covariance   = summary(model)$cov[2],
    var.slope    = summary(model)$cov[4],
    aic          = AIC(model),
    bic          = BIC(model),
    autocorr     = DW[[1]],
    dw_stat      = DW[[2]],
    dw_pval      = DW[[3]],
  lambda       = lambda
  )
  model.df = rbind(model.df,model.df.new)
}

summary(model.df)
```
Box Cox for each specimen model 
```{r}
summary(model.df[17])
ggplot(model.df,aes(lambda))+geom_histogram()+theme_bw()
ggplot(model.df,aes(lambda))+geom_density()+theme_bw()
```
Autocorrelation for each specimen model... nearly all have significant auto-correlation. The autocorrelation values are lower than expected, though. 
```{r}
model.df[14:16]
ggplot(model.df,aes(autocorr))+geom_histogram()+theme_bw()
ggplot(model.df,aes(autocorr))+geom_density()+theme_bw()
```


















```{r}
ggplot(as.data.frame(rho),aes(rho))+geom_density()+theme_bw()+ggtitle("Simulated Pearson Correlation")
ggplot(data.frame(stdev=stdev,index=c(1:numObservations)),aes(x=index,y=stdev))+geom_line()+theme_bw()+ggtitle("Simulated Random Error Standard Deviations")+ylim(0,4.5)+geom_hline(yintercept=0.3,linetype=3)

ggplot()+geom_density(aes(stdev),data=data.frame(stdev=stdev))+theme_bw()+ggtitle("Simulated Random Error Standard Deviations")



model.df.time.subsets=data.frame(
  sigma1= rgamma(n=numObservations/4,shape=7.8, rate=4.4),
  sigma2= rgamma(n=numObservations/4,shape=2.5, rate=3.3),
  sigma3= rgamma(n=numObservations/4,shape=3.7, rate=10.1),
  sigma4= rgamma(n=numObservations/4,shape=6.1, rate=20.2))


 ggplot(model.df.time.subsets)+geom_density(aes(sigma1),colour="red")+geom_density(aes(sigma2),colour="purple")+geom_density(aes(sigma3),colour="blue")+geom_density(aes(sigma4),colour="green")+theme_bw()+xlab("Standard Deviation")
 
 ggplot(model.df.time.subsets)+geom_density(aes(sigma1),colour="red")+geom_density(aes(sigma2),colour="purple")+geom_density(aes(sigma3),colour="blue")+geom_density(aes(sigma4),colour="green")+theme_bw()+xlab("Standard Deviation")+geom_density(aes(stdev),data=data.frame(stdev=stdev))


params_df = data.frame(
  specimen=c(1:numSpecimens),
  b0xt=b0xt,
  b1xt=b1xt,
  b0xy=b0xy,
  b1xy=b1xy,
  b0ty=b0ty,
  b1ty=b1ty)

p1=ggplot(params_df)+geom_density(aes(b0xt))+theme_bw()
p4=ggplot(params_df)+geom_density(aes(b1xt))+theme_bw()
p2=ggplot(params_df)+geom_density(aes(b0ty))+theme_bw()
p5=ggplot(params_df)+geom_density(aes(b1ty))+theme_bw()
p3=ggplot(params_df)+geom_density(aes(b0xy))+theme_bw()
p6=ggplot(params_df)+geom_density(aes(b1xy))+theme_bw()

grid.arrange(p1,p2,p3,p4,p5,p6,nrow=2)

p1=ggplot(data.ts)+geom_line(aes(x=x,y=y,colour=as.factor(specimen)),show.legend=FALSE)+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))
p2=ggplot(data.ts)+geom_line(aes(x=x,y=y.orig,colour=as.factor(specimen)),show.legend=FALSE)+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))
p3=ggplot(data.ts)+geom_line(aes(x=x,y=y.trans,colour=as.factor(specimen)),show.legend=FALSE)+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))

p4=ggplot(data.ts)+geom_line(aes(x=time,y=y,colour=as.factor(specimen)),show.legend=FALSE)+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))
p5=ggplot(data.ts)+geom_line(aes(x=time,y=y.orig,colour=as.factor(specimen)),show.legend=FALSE)+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))
p6=ggplot(data.ts)+geom_line(aes(x=time,y=y.trans,colour=as.factor(specimen)),show.legend=FALSE)+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))

grid.arrange(p1,p2,p3,p4,p5,p6,nrow=2)

p1=ggplot(data.ts)+geom_density(aes(x=y,colour=as.factor(specimen)),show.legend=FALSE)+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))
p2=ggplot(data.ts)+geom_density(aes(x=y.orig,colour=as.factor(specimen)),show.legend=FALSE)+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))
p3=ggplot(data.ts)+geom_density(aes(x=y.trans,colour=as.factor(specimen)),show.legend=FALSE)+theme_bw()+scale_color_manual(values=rainbow(numSpecimens))

grid.arrange(p1,p2,p3)

p1=ggplot(data.ts,(aes(x=x,y=time,colour=as.factor(specimen))))+geom_line(show.legend=FALSE)+theme_bw()+xlim(-1,3)+scale_color_manual(values=rainbow(numSpecimens))
p2=ggplot(data.ts,(aes(x=x,colour=as.factor(specimen))))+geom_density(show.legend=FALSE)+theme_bw()+xlim(-1,3)+scale_color_manual(values=rainbow(numSpecimens))

grid.arrange(p1,p2)

```
